config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  get 'signup', to: 'users#new'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'

  resources :users, only: [:new, :create]
  resources :transactions
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/transaction.rb
class Figure < ApplicationRecord
  validates :date, :transaction_type, :amount, :category, :description, presence: true
  
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    
    validates :email, presence: true, uniqueness: true
    validates :name, :password, presence: true
  
    has_many :transactions
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include Pagy::Backend
    
    helper_method :current_user
    helper_method :user_signed_in?
    
    def current_user
      User.find_by(id: session[:user_id])
    end
    
    def user_signed_in?
      !current_user.nil?
    end
  
    def authenticate_user!
      redirect_to root_path, alert: t('common.auth.authenticate_user') unless user_signed_in?
    end
  end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_url, notice: t('.notice')
    else
      flash.now[:alert] = t('.alert')
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: t('.notice')
  end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :authenticate_user!, only: %i[new create]
  before_action :set_transaction, only: %i[show edit update]

  def index
    @pagy, @transactions = pagy(Transaction.all)
  end

  def show; end

  def new
    @transaction = Transaction.new
  end

  def create
    @transaction = current_user.transactions.new transaction_params
    if @transaction.save
      return redirect_to root_url, notice: t('.notice')
    end

    render :new
  end

  def edit; end

  def update
    if @transaction.update transaction_params
      return redirect_to @transaction, notice: t('.notice')
    end

    render :edit
  end

  private

  def transaction_params
    params.require(:transaction).permit(:date, :transaction_type, :amount, :category, :description)
  end

  def set_transaction 
    @transaction = Transaction.find params[:id]
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def new
        @user = User.new
      end
    
      def create
        @user = User.new user_params
    
        if @user.save
          session[:user_id] = @user.id
          return redirect_to root_url, notice: t('.notice')
        end
    
        render :new
      end
    
      private
    
      def user_params
        params.require(:user).permit(:name, :email, :password)
      end
    end  

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    include Pagy::Frontend
    
    def flash_class(key)
      case key
        when 'notice' then 'is-success'
        when 'alert' then 'is-danger'
      end
    end
  end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/common/_flash_messages.html.erb
<% flash.each do |key, value| %>
  <div class="notification <%= flash_class(key) %>">
    <%= value%>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>My_Wallet</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'%>
  </head>

  <body>
    <%= render "navigation/navbar"%>
  
    <div class="container">
      <%= render "common/flash_messages"%>

      <%= yield %>
    </div>
  </body>
</html>

app/views/navigation/_navbar.html.erb
<nav class="navbar is-primary" role="navigation" aria-label="main navigation">
<div id="navbarBasicExample" class="navbar-menu">
  <div class="navbar-start">
    <%= link_to('Home', root_path, class: 'navbar-item') %>
    <%= link_to('Transactions', transactions_path, class: 'navbar-item') %>
  </div>

  <div class="navbar-end">
    <div class="navbar-item">
      <div class="buttons">
        <% if user_signed_in? %>
          <div class="navbar-item has-dropdown is-hoverable">
            <a class="navbar-link">
              <%= current_user.name %>
            </a>
            <div class="navbar-dropdown">
              <%= link_to('Salir', logout_path, class: 'navbar-item') %>
            </div>
          </div>
        <% else %>
          <%= link_to('Sign up', signup_path, class: 'button is-primary') %>
          <%= link_to('Log in', login_path, class: 'button is-light') %>
        <% end %>
      </div>
    </div>
  </div>
</div>
</nav>

app/views/transactions/_form.html.erb
<%= form_for @transaction, builder: BulmaFormBuilder do |f|%>
  <%= f.form_error %>

  <div class="field">
    <%= f.label :date, class: 'label' %>
    <div class="control">
      <%= f.text_field :date, class: 'input' %>
    </div>
    <%= f.field_error :date %>
  </div>

  <div class="field">
    <%= f.label :transaction_type, class: 'label' %>
    <div class="control">
      <%= f.text_field :transaction_type, class: 'input' %>
    </div>
    <%= f.field_error :transaction_type %>
  </div>
  <div class="field">
    <%= f.label :amount, class: 'label' %>
    <div class="control">
      <%= f.text_field :amount, class: 'input' %>
    </div>
    <%= f.field_error :amount %>
  </div>
   <div class="field">
    <%= f.label :category, class: 'label' %>
    <div class="control">
      <%= f.file_field :category, class: 'input' %>
    </div>
    <%= f.field_error :category %>
  </div>
  <div class="field">
    <%= f.label :description, class: 'label' %>
    <div class="control">
      <%= f.text_field :description, class: 'input' %>
    </div>
    <%= f.field_error :description %>
  </div>

  <%= f.submit class: 'button is-primary'%>
<% end %>

app/views/transactions/_transaction.html.erb
<div class="card column is-4">
  <div class="card-image">
    <% if figure.photo.attached? %>
      <figure class="image is-4by3">
        <%= image_tag(url_for(figure.photo))%>
      </figure>
    <% end %>
  </div>

  <div class="card-content">
    <div class="media">
      <div class="media-content">
        <p class="title is-4"><%= link_to( transaction.name, transaction_path(transaction))%></p>
        <p class="subtitle is-6"><%= transaction.date %> - <%= transaction.transaction_type %></p>
      </div>
    </div>
  </div>
</div>

app/views/transactions/create.html.erb
<h1>Transactions#create</h1>
<p>Find me in app/views/transactions/create.html.erb</p>

app/views/transactions/edit.html.erb
<h1 class="title" >Editar Transaction</h1>

<%= render 'form' %>

app/views/transactions/index.html.erb
<div class="columns is-desktop is-multiline">
  <%= render @transactions %>
</div>

<%== pagy_bulma_nav(@pagy) %>

app/views/transactions/new.html.erb
<h1 class="title" >New Transaction</h1>

<%= render 'form' %>

app/views/transactions/show.html.erb
<h1 class="title"><%= @transactrion.name %></h1>

<div class="content">
<br><hr>
  <ul>
    <li><%= @transaction.date %></li>
    <li><%= @ftransaction.transaction_type %></li>
    <li><%= @transaction.amount %></li>
    <li><%= @transaction.category %></li>
    <li><%= @transaction.description %></li>
  </ul>
</div>

app/views/transactions/update.html.erb
<h1>Transactions#update</h1>
<p>Find me in app/views/transactions/update.html.erb</p>

app/views/users/new.html.erb
<%= form_for @user do |f| %>

  <%- if @user.errors.any? %>
    <div class="notification is-danger">
      Oops!! parece que algo salio mal.
    </div>
  <% end %>
  
  <div class="field">
    <%= f.label :name, class: 'label' %>
    <div class="control">
      <%= f.text_field :name, class: 'input' %>
    </div>
  </div>
  </div class="field">  
     <%= f.label :name, class: 'label' %>

    <%= f.label :inscription %><br>
    <%= f.text_field :inscription %><br>

    <%= f.label :email %><br>
    <%= f.text_field :email %><br>

    <%= f.label :phone %><br>
    <%= f.text_field :phone %><br>

    <%= f.label :password %><br>
    <%= f.password_field :password %><br>

    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %><br>

    <%= f.submit class: 'button is-primary' %>
<% end %>

app/views/welcome/index.html.erb
<p>MI BILLETERA</p>